//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "oauth2_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub access_token: String,
    pub client_id: Uuid,
    pub user_id: Uuid,
    pub scope: String,
    pub expires_at: Option<DateTime>,
    pub revoked_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::oauth2_clients::Entity",
        from = "Column::ClientId",
        to = "super::oauth2_clients::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Oauth2Clients,
    #[sea_orm(has_many = "super::oauth2_refresh_tokens::Entity")]
    Oauth2RefreshTokens,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::oauth2_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth2Clients.def()
    }
}

impl Related<super::oauth2_refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth2RefreshTokens.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
