//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::oauth2_clients::Entity as Oauth2Clients;
pub use super::oauth2_codes::Entity as Oauth2Codes;
pub use super::oauth2_refresh_tokens::Entity as Oauth2RefreshTokens;
pub use super::oauth2_tokens::Entity as Oauth2Tokens;
pub use super::users::Entity as Users;
