//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub email: String,
    pub password: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::oauth2_codes::Entity")]
    Oauth2Codes,
    #[sea_orm(has_many = "super::oauth2_tokens::Entity")]
    Oauth2Tokens,
}

impl Related<super::oauth2_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth2Codes.def()
    }
}

impl Related<super::oauth2_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth2Tokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
